### PR TITLE
Feat/add scs course linuxhotel

### PR DESCRIPTION
**Pull request by garloff**

### CODE REVIEW

**Comment by garloff** [comment]
Deployment is on staging ... or more precisely: Will be shortly.

**Review by fkr — APPROVED** [review]
LGTM!

**Review by scoopex — APPROVED** [review]
LGTM, probably it would also a good idea to append the training partners to the https://staging.scs.community/website/de/partners/ page.

**Comment by garloff** [comment]
Followup PR #856

**Pull request merged**
