### PR TITLE
Improve wording (ephemeral disk). Live-Migr. consid.

### PR DESCRIPTION
**Pull request by garloff**
Also improve screenshot.

### CODE REVIEW

**Comment by Nils98Ar** [comment]
@garloff Maybe the term „ephemeral“ could be confusing as there already something called „Ephemeral Disk“ in the flavors. What about „[…], but disks managed directly by nova itself,[…]“?

The rest looks good to me!

**Comment by garloff** [comment]
> @garloff Maybe the term „ephemeral“ could be confusing as there already something called „Ephemeral Disk“ in the flavors. What about „[…], but disks managed directly by nova itself,[…]“?
> 
> The rest looks good to me!

Good point, while the treatment of root disks and ephemeral disks is very similar, the latter are not used as boot disks.
So let's avoid confusing them ...
PS: Does anyone use (additional) ephemera disks?

**Comment by Nils98Ar** [comment]
> PS: Does anyone use (additional) ephemera disks?

We only use cinder volume root disks right now.
And we only plan to use local SSD root disks for K8s etcd on the control planes and K8s ephemeral volumes on the worker nodes which are both located in the root filesystem by default.

Maybe it can be useful for database cluster node instances if you want separate root and data partitions…

**Comment by michaelbayr** [comment]
As @Nils98Ar said, there is a usecase for a database cluster where you would use additional ephemeral volumes to store the DB-Data on, but the root disk is a cinder volume. This architectecture allows you to easily failover databases to other hosts because the DB-Data is replicated by the database software. So there is no need to actually migrate this (ephemeral) data, but the database setup/configuration is still preserved across hosts/migrations.
I also find the "Root Disk"/"SSD Disk"/"Ephemeral Disk" naming confusing. We have a volume class called "ssd" which is replicated ssd storage in ceph (we also have hdd), and are doing local storage with NVMe (which has no "name"). But I think "ssd" is written down in the standards, so we won't be able to change that? (@garloff)
I would suggest that we always refer to "local disk"/"local storage"/"local ssd" when we talk about root disks on nova local storage. That way it can not be confused with additional ephemeral disks nor replicated storage.

**Comment by Nils98Ar** [comment]
@michaelbayr Also a good point. I didn't think about it because we don't have any HDDs. But isn't it just a naming thing and we can use "local ssd" everywhere (in the standards etc.) instead of just ssd?

**Comment by garloff** [comment]
> @garloff Maybe the term „ephemeral“ could be confusing as there already something called „Ephemeral Disk“ in the flavors. What about „[…], but disks managed directly by nova itself,[…]“?
> 
> The rest looks good to me!

This is improved now, thanks for the good feedback!

**Comment by garloff** [comment]
> I also find the "Root Disk"/"SSD Disk"/"Ephemeral Disk" naming confusing. We have a volume class called "ssd" which is replicated ssd storage in ceph (we also have hdd), and are doing local storage with NVMe (which has no "name"). But I think "ssd" is written down in the standards, so we won't be able to change that? (@garloff)
> I would suggest that we always refer to "local disk"/"local storage"/"local ssd" when we talk about root disks on nova local storage. That way it can not be confused with additional ephemeral disks nor replicated storage.

Care to point out where exactly we can improve the wording to avoid confusion?
Blog post? standards/scs-0110-v1-ssd-flavors? Matthias' suggested improvements?

**Comment by michaelbayr** [comment]
Blog Post is perfect now and was what I was referring to. 
standards/scs-0110-v1-ssd-flavors is already specific enough to point out that the SSDs have to be local storage. I don't know which improvements from Matthias you are referring to, but I can check if you want to link them.
If I run into another doc/description where I would want the "local" in front of the "ssd", I'll open a pull request on the respective page.

**Review by michaelbayr — APPROVED** [review]

**Comment by Nils98Ar** [comment]
Looks good now, also the clarification on live-migration!

**Review by Nils98Ar — APPROVED** [review]

**Pull request merged**
