### PR TITLE
fix(local_build): Rework the local build scripts

### LINKED ISSUE #964: Local build does not work anymore
The local build does not work anymore.

### PR DESCRIPTION
**Pull request by bitkeks**
Running `run-podman.sh` first creates an npm container, setting up the node_modules folder. Then it runs jekyll in a ruby 2.7 container, reading and building the website repo. Afterwards, the site can be looked at localhost:4000, with live-reloading and incremental rebuild enabled.

Resolves #964

### CODE REVIEW

**Comment by garloff** [comment]
Thanks for all the work.
The scripts to set up a local build env with podman ... all look good and useful to me, thanks.

One but: I see versions pinned in Gemfile that are older than the ones used for the build via github.
- Do we need to do our own version pinning? Can't we use the ones used by github?
- How do we keep the used gems ...  in sync ... ?

**Comment by garloff** [comment]
Conflict resolution, using latest minitest and activesupport.
(If that is not intended, please intervene!)

**Comment by bitkeks** [comment]
> One but: I see versions pinned in Gemfile that are older than the ones used for the build via github.

The only versions that need to be pinned for the build are the base image tags (`ruby:2.7-alpine`) and `bundler 2.4.22`. The `Gemfile.lock` was auto-updated, no veto from me to overwrite it with more up-to-date versions.

**Review by garloff — APPROVED** [review]
OK, good to go from my perspective.

**Pull request merged**
