### PR TITLE
Add employee profile pataky.md

### PR DESCRIPTION
**Pull request by bitkeks**
With redirect from /bitkeks to /pataky

### CODE REVIEW

**Comment by fkr** [comment]
ah, very good ;) The additions to the build-only.yml should probably be reverted thought.

**Comment by bitkeks** [comment]
> ah, very good ;) The additions to the build-only.yml should probably be reverted thought.

Failed again.. turns out, Jekyll does not evaluate the `Default` if the variable is not defined at all. Should work according to the docs at https://shopify.github.io/liquid/filters/default/ though, did not dig further.

Will revert the trace flag!

**Review by garloff — APPROVED** [review]
/lgtm

**Comment by bitkeks** [comment]
Needed to set DCO to "pass" manually, because some commit from main caused a conflict after merging into this feature branch.

**Review by scoopex — APPROVED** [review]
LGTM

**Pull request merged**
