### PR TITLE
Add Open Source Couch podcast episode with @fkr

### PR DESCRIPTION
**Pull request by itrich**
Signed-off-by: Eduard Itrich <eduard@itrich.net>

### CODE REVIEW

**Comment by fkr** [comment]
@itrich and I concluded, that this will be merged, once @itrich listened to the episode.

**Comment by garloff** [comment]
> @itrich and I concluded, that this will be merged, once @itrich listened to the episode.

OK, someone needs to hack @itrich's audio equipment now!

**Comment by itrich** [comment]
> > @itrich and I concluded, that this will be merged, once @itrich listened to the episode.
> 
> OK, someone needs to hack @itrich's audio equipment now!

You actually need to hack my toddlers that can't accept to hear anything else than child music during driving... However, I already listened to 50% of the episode.

**Review by fkr — APPROVED** [review]
LGTM. @itrich and I concluded, it is OK to merge.

**Pull request merged**
