### PR TITLE
Add first commit for the community hackathon blog post

### PR DESCRIPTION
**Pull request by ra-beer**
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

### CODE REVIEW

**Comment by itrich** [comment]
From my point of view, this PR is ready to be reviewed. Thank you @ra-beer for contributing 90% of the content!

@garloff @fkr @maxwolfs Did we miss anything? Feel free to contribute to the posting.

A life preview can be seen here: https://sovereigncloudstack.github.io/website/2023/03/31/hackathon-nuernberg/

**Review by maxwolfs — APPROVED** [review]
LGTM! Great Post!

**Comment by ra-beer** [comment]
@itrich Thank you for the great teamwork as usually. Without you work the post wouldn´t be so great. Thanks a lot!

**Review by fkr — APPROVED** [review]
Awesome post!

**Comment by garloff** [comment]
Very good!

**Pull request merged**
