### PR TITLE
Beautify community profile

### PR DESCRIPTION
**Pull request by itrich**

### CODE REVIEW

**Comment by itrich** [comment]
@fkr Would you mind creating yourself a community profile in this PR?

**Comment by fkr** [comment]
> @fkr Would you mind creating yourself a community profile in this PR?

done!

**Comment by itrich** [comment]
This is ready to be reviewed. Thank you @reqa, @frosty-geek, @fkr for your support and adopting this new feature very early!

**Review by maxwolfs — APPROVED** [review]
lgtm!

**Pull request merged**
