### PR TITLE
Add blog post on SIG IAM, openstack CLI and federation

### PR DESCRIPTION
**Pull request by reqa**
Signed-off-by: Arvid Requate <requate@univention.de>

### CODE REVIEW

**Comment by fkr** [comment]
@reqa would it make sense to include one of your diagrams?

**Comment by fkr** [comment]
@itrich  I think, your opinion on this post would be worthwhile as well.

**Comment by itrich** [comment]
I did some spell checking and added some quotes/headlines to reduce the wall of text impression.

**Review by itrich — CHANGES_REQUESTED** [review]
Please see #495 before merging this.

**Comment by itrich** [comment]
Just a side questions, @reqa: If there would be an option for a "About this author" section at the bottom of your blog posts with a short biography and some links to your open profiles, would you use this offering?

**Comment by reqa** [comment]
> Just a side questions, @reqa: If there would be an option for a "About this author" section at the bottom of your blog posts with a short biography and some links to your open profiles, would you use this offering?

Sure, can do. Is there an example where I could have a glance at the format/markup you would like to see there? I guess I should add it to this Pull Request?

**Comment by itrich** [comment]
> > Just a side questions, @reqa: If there would be an option for a "About this author" section at the bottom of your blog posts with a short biography and some links to your open profiles, would you use this offering?
> 
> Sure, can do. Is there an example where I could have a glance at the format/markup you would like to see there? I guess I should add it to this Pull Request?

Great to hear and thank you! I will prepare PR that adds an about section the "Jekyll way".

**Pull request merged**
