### PR TITLE
Let blockquote float right with 100% width

### PR DESCRIPTION
**Pull request by itrich**
This fixes logos overlapping the blockquote box.

2021-07-16 08_52_35-Window

### CODE REVIEW

**Comment by itrich** [comment]
I just realized that this change crumbles the last paragraph. I'll fix this asap.

**Comment by itrich** [comment]
I moved the latter paragraph "The complete statement..." up and set a cumulative width for the block-quote on desktop screens (so that we don't generate unnecessary white-space.)

**Comment by garloff** [comment]
Next to our home page, the press release (/News/pr20210713.html.(en|de)) also uses block quotes -- please double check that these continue to look reasonable. Thanks in advance!

**Comment by itrich** [comment]
> Next to our home page, the press release (/News/pr20210713.html.(en|de)) also uses block quotes -- please double check that these continue to look reasonable. Thanks in advance!

Thanks for the hint! As the width is fixed to 100% (beside the classes quote-gaia-x and quote-bmwi on desktop screens), the new style definitions don't change anything to the look of the press release.

**Comment by garloff** [comment]
Thanks for checking!

**Pull request merged**
