### PR TITLE
Feat/blog cpu vulns 202312

### PR DESCRIPTION
**Pull request by 90n20**

### CODE REVIEW

**Comment by 90n20** [comment]
Regarding the patch for AMD Cachewarp of Zen 3 processors, it is mentioned on [AMD INVD Security Advisory](https://www.amd.com/en/resources/product-security/bulletin/amd-sb-3005.html) as MilanPI 1.0.0.C
(Target Dec 2023), Milan B1 – 0x0A0011D1 and Milan-X B2 – 0x0A001234, but no links or further information is provided.

I only found references to this firmware versions on VMware update notes and on some motherboard vendors BIOS upgrades. No traces of it under ubuntu or other linux distributions.

**Review by garloff — APPROVED** [review]
I have added a few improvements.
Please review.
If you are happy, feel free to merge the PR, so it gets published.

**Comment by garloff** [comment]
You need to add a community profile, @90n20, with a picture and a few words about yourself.
See https://scs.community/2023/01/27/community-profiles/ for an explanation with community profiles.

**Comment by 90n20** [comment]
@garloff  I have added the corresponding profile and avatar, as well as modified the article to match profile information. If no more additions from your side, it is ready to merge for me.

**Comment by fkr** [comment]
@90n20 I just pushed it to the staging branch. If it builds correctly it will be available on the staging site soonish.
Here is the action that is currently running: https://github.com/SovereignCloudStack/website/actions/runs/7395099505

**Comment by 90n20** [comment]
Thanks @fkr seems that everything wents smoother and the staging site is showing both post and profile as expected.

**Comment by fkr** [comment]
@90n20 maybe update the date of the post today before merging?

**Pull request merged**
