### PR TITLE
Add security.txt according to RFC8615

### PR DESCRIPTION
**Pull request by itrich**
This PR adds a security.txt under `/` and `/.well-known` according to RFC8615. Content was generated by https://securitytxt.org/
Fixex #211.

### CODE REVIEW

**Comment by fkr** [comment]
Looks good to me.

**Comment by itrich** [comment]
> Looks good to me.
Yes, `/.well-known/security.txt` looks good, but I just realized that the plugin `jekyll-redirect-from` we're using creates this content for `/security.txt`:
```
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="http://localhost:4000/.well-known/security.txt">
  <script>location="http://localhost:4000/.well-known/security.txt"</script>
  <meta http-equiv="refresh" content="0; url=http://localhost:4000/.well-known/security.txt">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <a href="http://localhost:4000/.well-known/security.txt">Click here if you are not redirected.</a>
</html>
```

I don't know how to make the file available under multiple permalinks. Should we just drop `/security.txt`?

**Comment by fkr** [comment]
I'd place it in /.well-known/security.txt and have something in place that copies it to /security.txt as part of the jekyll build process. that way it only needs to be mainted in one place, we avoid using the plugin and it is also available via /security.txt

**Comment by itrich** [comment]
> I'd place it in /.well-known/security.txt and have something in place that copies it to /security.txt as part of the jekyll build process. that way it only needs to be mainted in one place, we avoid using the plugin and it is also available via /security.txt

Good idea! See my latest commit.

**Pull request merged**
