### PR TITLE
Add lato font via npm and use it for <body>

### PR DESCRIPTION
**Pull request by itrich**
Signed-off-by: Eduard Itrich <eduard@itrich.net>

### CODE REVIEW

**Comment by itrich** [comment]
Thank you @maxwolfs for today's sessions. We finally managed to implement lato by using `npm` and integrating this with our Jekyll asset pipeline :partying_face:

**Comment by itrich** [comment]
> node_modules folder should be added to gitignore otherwise nice!

I'd disagree. In order to reduce build time in our GitHub Actions, we've pushed all node modules directly to the repository. Especially when running build tests with every push, this will shred our free quota of using GitHub Actions.

**Comment by maxwolfs** [comment]
> > node_modules folder should be added to gitignore otherwise nice!
> 
> I'd disagree. In order to reduce build time in our GitHub Actions, we've pushed all node modules directly to the repository. Especially when running build tests with every push, this will shred our free quota of using GitHub Actions.

Ok I see, but isn't this an antipattern, especially if there are more modules being added overtime? The git history will be inflated with peer dependencies of dependencies which might led to security issues aswell as maintenance issues and potential bigger scale merge conflicts.

**Comment by itrich** [comment]
> > > node_modules folder should be added to gitignore otherwise nice!
> > 
> > 
> > I'd disagree. In order to reduce build time in our GitHub Actions, we've pushed all node modules directly to the repository. Especially when running build tests with every push, this will shred our free quota of using GitHub Actions.
> 
> Ok I see, but isn't this an antipattern, especially if there are more modules being added overtime? The git history will be inflated with peer dependencies of dependencies which might led to security issues aswell as maintenance issues and potential bigger scale merge conflicts.

I created a separate issue to discuss this change and would suggest to keep the node_modules at least for this PR.

**Review by maxwolfs — APPROVED** [review]

**Pull request merged**
