### PR TITLE
Drop rsync action and rather use git pull

### PR DESCRIPTION
**Pull request by itrich**
This change drops the rsync action and pushes the website build output to the repository. We thus will need to regularly pull the branch `gh-pages` onto the webserver.

Signed-off-by: Eduard Itrich <eduard@itrich.net>

### CODE REVIEW

**Comment by itrich** [comment]
Alternatively, we could deploy our website with GitHub Pages, but this should imho be discussed regarding privacy concerns and dependencies.

**Comment by fkr** [comment]
I'd rather not switch to gh pages. We deploy various items to the website - check with @garloff. Rather work with submodules and deploy from there.

**Comment by garloff** [comment]
I see how the built pages are committed into the gh-pages branch of the repo, from which I can pull on the web server.
How do we trigger this?
Or is your idea to git pull every 5mins?

**Comment by itrich** [comment]
> I see how the built pages are committed into the gh-pages branch of the repo, from which I can pull on the web server. How do we trigger this? Or is your idea to git pull every 5mins?

Yes, the idea is to force git pull every x minutes into the right directory on the web server. We'll loose some minutes in the whole pipeline, but we don't have to struggle with rsync destroying directories or feat of leaking ssh keys.

**Comment by garloff** [comment]
How do we move this forward and conclude it?
Should I pull the gh-pages branch on the web server and then just start docker with that directory instead to test whether it works as designed?

**Comment by itrich** [comment]
> How do we move this forward and conclude it? Should I pull the gh-pages branch on the web server and then just start docker with that directory instead to test whether it works as designed?

Please let me know when you'll be free to test this. I'll then merge this PR so that the website gets pushed again to the `gh-pages` branch. We will need a cronjob to regullarly pull the `gh-pages` branch into the webserver's directory.

**Pull request merged**
