### PR TITLE
start working on a blogpost that outlines r4 outcomes

### PR DESCRIPTION
**Pull request by fkr**
Signed-off-by: Felix Kronlage-Dammers <fkr@hazardous.org>

### CODE REVIEW

**Comment by itrich** [comment]
/remind me to merge this PR on 2022-11-02 08:00:00

**Comment by fkr** [comment]
@garloff are you finished adding items to this PR?

**Comment by fkr** [comment]
> /remind-me Wednesday 9am Merge this PR

Please not. I was waiting until @garloff finished adding items to this PR in order to then give it final polishing.

**Comment by fkr** [comment]
@itrich from my side, good to be published. 
@garloff you want to read over the final version? Especially since I've added you as the author.

**Comment by garloff** [comment]
Looks really good to me now.

**Review by garloff — APPROVED** [review]
/lgtm

**Pull request merged**
