### PR TITLE
Add an overview of our ecosystem

### PR DESCRIPTION
**Pull request by itrich**
This PR adds an overview of our service partner ecosystem. We have received two contributions so far. More content is likely to be added soon.

The overview build using `cards`:

The detail page per service partner (inspired by the page per employee):

What's your impression? Is something missing? What should be added or changed?

I refrained from adding telephone numbers or mail addresses as they might change and point into nil.

The following things are on my to-do-list but won't be delivered in this very first MVP:
- Filter the cards in the overview by their categories
- Add an umbrella text beneath the "service partners" headline

CC @janiskemper @batistein @johntaylorsc

### CODE REVIEW

**Comment by johntaylorsc** [comment]
Thanks for sending me the output. In the original request, I had provided a (bulleted) list for the various services. I see this has been parsed into a paragraph and I may need to add some better punctuation to make sense. How should I provide this? 

 

John

 

From: Eduard Itrich ***@***.***> 
Sent: 17 May 2022 10:44
To: SovereignCloudStack/website ***@***.***>
Cc: John Taylor ***@***.***>; Mention ***@***.***>
Subject: [SovereignCloudStack/website] Add an overview of our ecosystem (PR #301)

 

This PR adds an overview of our service partner ecosystem. We have received two contributions so far. More content is likely to be added soon.

The overview build using cards:
 <https://user-images.githubusercontent.com/29982899/168780969-02b41838-70ef-4ac8-80bb-6bf3ae94cb86.png> 

The detail page per service partner (inspired by the page per employee):
 <https://user-images.githubusercontent.com/29982899/168781186-e45a1904-e7c8-48a2-96d5-37cfbfa5fd7c.png> 

What's your impression? Is something missing? What should be added or changed?

I refrained from adding telephone numbers or mail addresses as they might change and point into nil.

The following things are on my to-do-list but won't be delivered in this very first MVP:

*	Filter the cards in the overview by their categories
*	Add an umbrella text beneath the "service partners" headline

CC @janiskemper <https://github.com/janiskemper>  @batistein <https://github.com/batistein>  @johntaylorsc <https://github.com/johntaylorsc> 

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/SovereignCloudStack/website/pull/301


Commit Summary


*	e7e4140 <https://github.com/SovereignCloudStack/website/pull/301/commits/e7e41403c24a6a385e1906b4cac485759f45e979>  Add first draft for ecosystem
*	60845f4 <https://github.com/SovereignCloudStack/website/pull/301/commits/60845f45155e3f43a13e18f8cf7394a4511b0e6a>  Change headline of ecosystem
*	76df5a1 <https://github.com/SovereignCloudStack/website/pull/301/commits/76df5a1cebfe68145c61420b881f40b662e0bafa>  Add one page per service partner


File Changes 


(9 <https://github.com/SovereignCloudStack/website/pull/301/files>  files)

*	A _data/partner.yml <https://github.com/SovereignCloudStack/website/pull/301/files#diff-1eb04c936f730a7653bb7655706e9f6819309cb48bf13fbe23b5c8f11dfb8d0f>  (26) 
*	A _includes/ecosystem.html <https://github.com/SovereignCloudStack/website/pull/301/files#diff-a5937b4e000e7f8afdf63a6e5c5d04ec76b4eb80e8b2647d0451210fd257217d>  (19) 
*	M _layouts/jobs.html <https://github.com/SovereignCloudStack/website/pull/301/files#diff-9965254881b213ea74551686bc6b31b4cb39778793307cd7cb820fcfe1ba0da9>  (2) 
*	A _layouts/partner.html <https://github.com/SovereignCloudStack/website/pull/301/files#diff-6b02bfdc5d467a06a1b095c107df33f533a7aac70df66c0a34213e08875255d6>  (49) 
*	M _pages/community.md <https://github.com/SovereignCloudStack/website/pull/301/files#diff-5bd98ea7e2e85c3867b549664c75e503eabe18ce8a012bb763d651187d274d8b>  (4) 
*	A _pages/partner/stackhpc.md <https://github.com/SovereignCloudStack/website/pull/301/files#diff-582d2fff60e306a5099f1a09e64ad8e132918dab8127099ac1655c042ec91734>  (5) 
*	A _pages/partner/syself.md <https://github.com/SovereignCloudStack/website/pull/301/files#diff-25a5b4e497d915e6da13c04023986dbf385b3aa12b424cfec5f7b54397c53f30>  (5) 
*	M assets/css/_sass/custom.scss <https://github.com/SovereignCloudStack/website/pull/301/files#diff-187706c07a2606701362bdcbfadffd8c6cd58baa27f9d3ffa217ee2c93770d7b>  (9) 
*	A assets/images/logo-syself.svg <https://github.com/SovereignCloudStack/website/pull/301/files#diff-c12c6fc47968ffb3d76e442ca9140d6b3a4851f0135c77893e7bdfb2612f6026>  (112) 


Patch Links:


*	https://github.com/SovereignCloudStack/website/pull/301.patch
*	https://github.com/SovereignCloudStack/website/pull/301.diff

**Comment by itrich** [comment]
> Thanks for sending me the output. In the original request, I had provided a (bulleted) list for the various services. I see this has been parsed into a paragraph and I may need to add some better punctuation to make sense. How should I provide this? 

You can either fork this repository and create a Pull Request against this branch or simply send me a mail with your desired content. 

Thank your for your feedback!

**Comment by johntaylorsc** [comment]
Hi Eduard,

 

Looks like I don’t have write access to the repository.

 

John

**Comment by itrich** [comment]
You should have received an invite as contributor to @SovereignCloudStack. Let me know if I can help you further. 😊

**Review by fkr — APPROVED** [review]
LGTM

**Pull request merged**
