### PR TITLE
Proofreading of about section

### PR DESCRIPTION
**Pull request by itrich**
Signed-off-by: Eduard Itrich <eduard@itrich.net>

### CODE REVIEW

**Comment by garloff** [comment]
Comments:
(a) I believe federatable is the best translation of "föderierbar" whether or not this word exists officially yet ...
(b) Use a branch name with prefix fix/ or feat/ to indicate whether this is a new contribution (feature) or a fix ..

**Comment by garloff** [comment]
Thanks, Eduard!

**Comment by itrich** [comment]
> Comments:
> (a) I believe federatable is the best translation of "föderierbar" whether or not this word exists officially yet ...

After researching again on whether 'federable' or 'federatable' is more commonly used, I've to agree with you. I'll fix this with the next PR.
> (b) Use a branch name with prefix fix/ or feat/ to indicate whether this is a new contribution (feature) or a fix ..

I named the branch `fix/proofreading`. Shall I also name the pull request on GitHub `fix/proofreading`?

**Comment by garloff** [comment]
Hi Eduard,

> I named the branch fix/proofreading. Shall I also name the pull request on GitHub fix/proofreading?

I should have looked more closely, sorry. No idea why the PR labeler complained then ...

**Pull request merged**
