### PR TITLE
close #751: add artcodix

### LINKED ISSUE #751: artcodix missing on the map
SSIA

hints:

_data/supporter.yml
image

### PR DESCRIPTION
**Pull request by scoopex**

### CODE REVIEW

**Comment by scoopex** [comment]
Not sure if the logos are okay. Can anybody from artcodix check them and provide better ones if neccessary?

**Comment by fkr** [comment]
this [commit](https://github.com/SovereignCloudStack/website/commit/40c76c21e2307f9e2cd336f2dcacaa27de6c27a0) added the logo that was provided by Artcodix.

**Comment by garloff** [comment]
Commit looks good to me, but I'll leave it for @michaelbayr to decide whether he wants the SVG or a higher res PNG as artcodix logo here.

**Comment by scoopex** [comment]
Lets merge this and fix the icons later (if necessary, fyi @michaelbayr) to reduce the efforts for this.
The preview at https://staging.scs.community/website/de/ looks not perfect but also not bad....

**Review by manuela-urban — APPROVED** [review]
lg enough tm!

**Comment by michaelbayr** [comment]
Sorry for my late reply. I was sick out of office all of last week. 
Looks great on the staging site! We plan on moving location soonish - when we do, I'll provide the new address and improved icon if necessary. Until then, this is perfect.
Thanks for putting us up!

**Pull request merged**
